-- Creacion de tablespaces Datos - Indices --

CREATE TABLESPACE DATOS
DATAFILE 'E:\app\mbravo\virtual\oradata\orcl\DATOS' SIZE 32000M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE INDICES
DATAFILE 'E:\app\mbravo\virtual\oradata\orcl\INDICES' SIZE 16000M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
