-- creracion de esquema de BD ---

create USER SIXDES40
 IDENTIFIED BY "sixdes40$"
 DEFAULT TABLESPACE DATOS
  temporary tablespace TEMP

grant unlimited tablespace to  SIXDES40 


GRANT CONNECT TO SIXDES40;
GRANT RESOURCE TO SIXDES40;

GRANT ALTER ANY SEQUENCE TO SIXDES40 WITH ADMIN OPTION;

GRANT ALTER ANY TABLE TO SIXDES40 WITH ADMIN OPTION;

GRANT ALTER ANY TRIGGER TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE ANY INDEX TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE ANY JOB TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE ANY MATERIALIZED VIEW TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE ANY PROCEDURE TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE ANY SEQUENCE TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE ANY SYNONYM TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE ANY TABLE TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE ANY TRIGGER TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE ANY VIEW TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE JOB TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE MATERIALIZED VIEW TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE PROCEDURE TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE PUBLIC SYNONYM TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE TABLE TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE TRIGGER TO SIXDES40 WITH ADMIN OPTION;

GRANT CREATE VIEW TO SIXDES40 WITH ADMIN OPTION;

